---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # Codes that Windows might use to say it's rebooting.
  # We need the retry logic or chef will see the reboot
  # as a complete failure and give up.
  retry_on_exit_code: [35, 259]
  max_retries: 3
  wait_for_retry: 180
  client_rb:
    exit_status: :enabled
    client_fork: false
verifier:
  name: inspec

platforms:
  - name: centos-7.3
  - name: ubuntu-16.04
    # To run test-kitchen for OS X, create a box for 10.10, and add it to vagrant
  - name: macosx-10.10
    driver_config:
      box: chef/macosx-10.10
  - name: windows-2012r2
    driver_config:
      box: mwrock/Windows2012R2

suites:
<% %w(13 14).each do |version| %>
  - name: default_chef<%= version %>
    provisioner:
      require_chef_omnibus: <%= version %>
    run_list:
      - recipe[test]
    attributes:
<% end %>
  - name: windows_location
    provisioner:
      require_chef_omnibus: 13
    run_list:
     - recipe[test::windows_location]
    includes:
      - windows-2012r2
    attributes:
