---
jobs:
  final:
    docker:
      - image: bash:latest
    steps:
      - run:
          name: Finish cooking
          command: echo "Finished cooking"
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2
workflows:
  kitchen:
    jobs:
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery
      - kitchen/dokken-single:
          name: default-centos-7
          suite: default-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-ubuntu-1804
          suite: default-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: generic-centos-7
          suite: generic-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: generic-ubuntu-1804
          suite: generic-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: uninstall-ubuntu-1804
          suite: uninstall-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: genericuninstall-ubuntu-1804
          suite: genericuninstall-ubuntu-1804
          requires: *lint_and_unit
      - final:
          requires:
            - default-centos-7
            - default-ubuntu-1804
            - generic-centos-7
            - generic-ubuntu-1804
            - uninstall-ubuntu-1804
            - genericuninstall-ubuntu-1804
