---
name: Branch Cleanup
# This workflow is trigged on all closed pull requests, it does something only if a merge is performed.
on:
  pull_request:
    types: [closed]

env:
  NO_BRANCH_DELETED_EXIT_CODE: 0
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jessfraz/branch-cleanup-action@master
